# Generated by Django 3.2.20 on 2024-05-27 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatbot',
            new_name='Chat',
        ),
    ]
